//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Utility.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length parameter cannot be negative..
        /// </summary>
        internal static string RandomExtensions_NextString_Error_NegativeLength {
            get {
                return ResourceManager.GetString("RandomExtensions_NextString_Error_NegativeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source characters have been provided to generate a random string from..
        /// </summary>
        internal static string RandomExtensions_NextString_Error_NoCharactersToSelectFrom {
            get {
                return ResourceManager.GetString("RandomExtensions_NextString_Error_NoCharactersToSelectFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The count parameter cannot be negative..
        /// </summary>
        internal static string RandomExtensions_NextStringSet_Error_NegativeCount {
            get {
                return ResourceManager.GetString("RandomExtensions_NextStringSet_Error_NegativeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A length generator function must be provided..
        /// </summary>
        internal static string RandomExtensions_NextStringSet_Error_NullLengthGenerator {
            get {
                return ResourceManager.GetString("RandomExtensions_NextStringSet_Error_NullLengthGenerator", resourceCulture);
            }
        }
    }
}
