//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unicorn.FontTools.OpenType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unicorn.FontTools.OpenType.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data to load &apos;cmap&apos; table..
        /// </summary>
        internal static string CharacterMappingTable_FromBytes_InsufficientLength {
            get {
                return ResourceManager.GetString("CharacterMappingTable_FromBytes_InsufficientLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded value is too large to be converted to a timestamp..
        /// </summary>
        internal static string Extensions_ByteArrayExtensions_ToDateTime_OutOfRangeError {
            get {
                return ResourceManager.GetString("Extensions_ByteArrayExtensions_ToDateTime_OutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field elements must all be within the range of an unsigned 16-bit integer..
        /// </summary>
        internal static string FieldValidation_ValidateArrayOfUShortParameter_Error {
            get {
                return ResourceManager.GetString("FieldValidation_ValidateArrayOfUShortParameter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must not be less than zero..
        /// </summary>
        internal static string FieldValidation_ValidateNonNegativeIntParameter_Error {
            get {
                return ResourceManager.GetString("FieldValidation_ValidateNonNegativeIntParameter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must not be less than zero..
        /// </summary>
        internal static string FieldValidation_ValidateNonNegativeLongParameter_Error {
            get {
                return ResourceManager.GetString("FieldValidation_ValidateNonNegativeLongParameter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be within the range of an unsigned 32-bit integer..
        /// </summary>
        internal static string FieldValidation_ValidateUIntParameter_Error {
            get {
                return ResourceManager.GetString("FieldValidation_ValidateUIntParameter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be within the range of an unsigned 16-bit integer..
        /// </summary>
        internal static string FieldValidation_ValidateUShortParameter_Error {
            get {
                return ResourceManager.GetString("FieldValidation_ValidateUShortParameter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data to load &apos;head&apos; table..
        /// </summary>
        internal static string HeaderTable_FromBytes_InsufficientDataError {
            get {
                return ResourceManager.GetString("HeaderTable_FromBytes_InsufficientDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High byte array of incorrect length..
        /// </summary>
        internal static string HighByteSubheaderCharacterMapping_FromBytes_ArrayLengthError {
            get {
                return ResourceManager.GetString("HighByteSubheaderCharacterMapping_FromBytes_ArrayLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data to load &apos;hhea&apos; table..
        /// </summary>
        internal static string HorizontalHeaderTable_FromBytes_InsufficientDataError {
            get {
                return ResourceManager.GetString("HorizontalHeaderTable_FromBytes_InsufficientDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data to load &apos;maxp&apos; table..
        /// </summary>
        internal static string MaximumProfileTable_FromBytes_InsufficientDataError {
            get {
                return ResourceManager.GetString("MaximumProfileTable_FromBytes_InsufficientDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding not supported..
        /// </summary>
        internal static string NamingTable_FromBytes_EncodingNotSupportedMessage {
            get {
                return ResourceManager.GetString("NamingTable_FromBytes_EncodingNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data to load &apos;name&apos; table..
        /// </summary>
        internal static string NamingTable_FromBytes_InsufficientDataError {
            get {
                return ResourceManager.GetString("NamingTable_FromBytes_InsufficientDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following data tables are missing: {0}..
        /// </summary>
        internal static string OpenTypeFont_CheckTablesPresent_MissingTablesError {
            get {
                return ResourceManager.GetString("OpenTypeFont_CheckTablesPresent_MissingTablesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetTable not loaded..
        /// </summary>
        internal static string OpenTypeFont_CheckValidity_MissingHeaderError {
            get {
                return ResourceManager.GetString("OpenTypeFont_CheckValidity_MissingHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown magic number {0}..
        /// </summary>
        internal static string OpenTypeFont_LoadOffsetTable_UnknownMagicError {
            get {
                return ResourceManager.GetString("OpenTypeFont_LoadOffsetTable_UnknownMagicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess character mapping data provided..
        /// </summary>
        internal static string PlainByteCharacterMapping_FromBytes_ArrayTooLarge {
            get {
                return ResourceManager.GetString("PlainByteCharacterMapping_FromBytes_ArrayTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient character mapping data provided..
        /// </summary>
        internal static string PlainByteCharacterMapping_FromBytes_ArrayTooSmall {
            get {
                return ResourceManager.GetString("PlainByteCharacterMapping_FromBytes_ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate glyph name found when loading PostScript information..
        /// </summary>
        internal static string PostScriptTable_DuplicateGlyphNameError {
            get {
                return ResourceManager.GetString("PostScriptTable_DuplicateGlyphNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag values must be four characters long..
        /// </summary>
        internal static string Tag_Constructor_ArrayLengthError {
            get {
                return ResourceManager.GetString("Tag_Constructor_ArrayLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No character mapping data provided..
        /// </summary>
        internal static string TrimmedTableCharacterMapping_FromBytes_ArrayEmpty {
            get {
                return ResourceManager.GetString("TrimmedTableCharacterMapping_FromBytes_ArrayEmpty", resourceCulture);
            }
        }
    }
}
